name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore XirzoDIContainer.Tests/XirzoDIContainer.Tests.csproj

    - name: Build
      run: dotnet build XirzoDIContainer.Tests/XirzoDIContainer.Tests.csproj --no-restore

    - name: Test
      run: dotnet test XirzoDIContainer.Tests/XirzoDIContainer.Tests.csproj --no-build --collect:"XPlat Code Coverage"
